platform :ios, '7.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'Reachability', '~> 3.1.1'
pod 'AFNetworking', '~> 2.2'
pod 'TPKeyboardAvoiding', '~> 1.2'
pod 'PubNub', '~> 3.6'
pod 'Bugsnag', '~> 3.1'
pod 'JSQMessagesViewController', '~> 5.0'